### ISSUE TITLE
[Not Confirmed] Registration defaulting user role to admin.

### ISSUE THREAD

**Issue by ethsmith** [bytepowered/LaraFlex#1]
Haven't looked at this much but I THINK users that register can access the admin panel because it defaults there role to admin and not subscriber it is not confirmed and maybe it was a mistake on my end and not the software but still needs looked at. This is why a LaraFlex snapshot isn't available for download yet. :P

**Comment by TheDiamondYT1** [comment]
Nice

**Comment by ethsmith** [comment]
Actually I don't think this is a bug, I think my session didn't expire so I still had admin perms haha.

**Comment by TheDiamondYT1** [comment]
Can I haz  ~~cheeseburger ~~ organization owner
