### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TheDiamondYT1** [bytepowered/LaraFlex#2]
Can i haz ~~cheeseburger~~ organization owner?

**Comment by TheDiamondYT1** [comment]
@TekkitCommando

**Comment by ethsmith** [comment]
@TheDiamondYT1 Why would you need owner? You have repo access. All you get with owner is repo creation and managing users.

**Comment by TheDiamondYT1** [comment]
Exactly, creation.

**Comment by ethsmith** [comment]
@TheDiamondYT1 I mean yeah but it is kind of unnecessary xD Anyways you have owner now.

**Comment by TheDiamondYT1** [comment]
Yay, I now haz ~~cheeseburger~~ owner!
